database:
    type: postgres
    host: "localhost"
    port: 5432
    name: "status-bot"

logging:
    format: human
    level: info
    uvicorn_access: false

bot:
    name: 'status-bot'
    chat_key: "zQ3..Example"
    bot_hash_pepper: '' # Use a large random value

backend:
    domain: "localhost"
    backend_port: 8080
    is_secure: false

api:
    enable: true
    host: "0.0.0.0"
    port: 8081
    # api_key: "your-secret-key"

modules:
    directories: []
    enabled: ["messaging", "receiver", "community_monitoring", "discourse_bridge"]
    settings:
        receiver:
            messages_table: "received_messages"
            chats_table: "received_chats"
        community_monitoring:
            interval: 900
            schema: "status_app_monitoring"
            detoxify: true
            communities:
                - Status
                - Logos
        discourse_bridge:
            category_name: "discuss.status.app"
            delay: 5 # Seconds to wait between every sent Discourse message
            emoji_shortname: ":white_check_mark:"
            api:
                key: ""
                username: ""
            content_type:
                - 1 # Text
            url:
                discourse: "https://discuss.status.app"
                community: "https://status.app/c/G4AAAGRgngMUmea2VZcKn0rXyYHD8aLfDhfKwgQjSfIcPp8kbltM_SnmM1mZYyCpzU0LaELQRRnrfDz_Hrf-8ojM-j3ffyYNTcn9sZZx3ef-eMLkNMx3M0M9zN705o8MzMadJCuatPRgUXUB#zQ3shqYasmP7ZHvAWvG1J9hG5XrH2qV7Xs3CFDu3mCRuuXrKk"

metrics:
    enabled: true
    host: "0.0.0.0"
    port: 8000
