postgres:
    schema: "status_app_monitoring"
    tables:
        messages: "raw_messages"
        community: "raw_community_info"
        members: "raw_community_activity"
# Value must be in MINUTES
sleep: 10
files:
    # Get the latest community chat dates for next run
    current_state: "dates.pkl"
# Parameters based on Account class
bot_params:
    # localhost - to run code locally with Status Backend Dockerfile
    # status-backend - to run code with docker-compose.yaml
    domain: "status-backend"
    port: 8080
    is_secure: false
