---
services:
    status-backend:
        image: harbor.status.im/bi/status-backend:dev
        container_name: status-backend
        ports:
            - 8080:8080
            - 8545:8545
            - 30303:30303
        entrypoint: 'status-backend'
        command: '-address 0.0.0.0:8080'
        volumes:
            - ./backups:/root/.config/Status/backups
        networks:
            - status-bridge
        profiles:
            - backend
            - monitoring
            - account-creation
    status-account-creation:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: account-creation
        command: 'python create_account.py'
        depends_on:
            - status-backend
        env_file:
            - .env
        volumes:
            - ./accounts:/app/accounts
        networks:
            - status-bridge
        profiles:
            - account-creation
    status-monitor:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: message-processing
        depends_on:
            - status-backend
        env_file:
            - .env
        environment:
            STATUS_BACKEND_HOST: status-backend
        volumes:
            - ./accounts:/app/accounts
        profiles:
            - monitoring
        networks:
            - status-bridge

networks:
    status-bridge:
        name: status-bridge
        driver: bridge
