[project]
name = "status-bot"
version = "1.0.0-RC1"
description = "A modular bot for Status App that automates tasks, responds to commands, and integrates with APIs."
requires-python = ">=3.12"
license-files = ["LICENSE.md"]
authors = [{name = "status-im"}]
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "pydantic-settings",
    "python-dotenv",
    "psycopg2-binary",
    "sqlalchemy",
    "prometheus-client",
    "status-sdk @ git+https://github.com/status-im/status-python-sdk.git@164f439bdee3b88e36664b7ee977aa384b7d6257",
    "pyyaml",
    "pandas",
]

[project.optional-dependencies]
dev = ["pytest"]
docs = [
    "mkdocs>=1.5.3",
    "mkdocs-material>=9.5.0",
]

[project.scripts]
status-bot = "main:main"

[build-system]
requires = ["setuptools>=70.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["status_bot", "status_bot.*"]
